### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "external-helpers"

### ISSUE THREAD

**Issue by wyhaya** [hilongjw/vue-lazyload#233]
`Error`:
```bash
ERROR in ./node_modules/vue-lazyload/vue-lazyload.js
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/Users/WYH/Desktop/test/node_modules/vue-lazyload/.babelrc" at 0, attempted to resolve relative to "/Users/WYH/Desktop/test/node_modules/vue-lazyload"
    at /Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/WYH/Desktop/test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/WYH/Desktop/test/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/WYH/Desktop/test/node_modules/babel-loader/lib/index.js:173:20)
 @ ./src/index.js 3:0-23
error Command failed with exit code 2.
```
`package.json`
```json
{
  "scripts": {
    "dev": "webpack --config webpack.config.dev.js --mode development"
  },
  "devDependencies": {
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.12"
  },
  "dependencies": {
    "vue-lazyload": "^1.2.2"
  }
}
```
`.babelrc`
```json
{
    "presets": [
        "env"
    ]
}
```
`webpack.config.dev.js`
```javascript
// ...
rules: [
    {
        test: /\.js$/,
        loaders: ['babel-loader']
     }
]
```
`index.js`
```javascript
require('vue-lazyload')
console.log('Test')
```

**Comment by hilongjw** [comment]
configure your webpack js loader to exclude modules from node_modules

```javascript
{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      }
```

**Comment by wyhaya** [comment]
Thank you

**Comment by oulaly** [comment]
I tried this: exclude: /vue-lazyload/ from webpack js loader, it works.

**Comment by zyprepare** [comment]
But some plugins are written in ES6 syntax and need compiling.
